export const ACCOUNT_ADD_REQUEST = 'ACCOUNT_ADD_REQUEST'
export const ACCOUNT_ADD_SUCCESS = 'ACCOUNT_ADD_SUCCESS'
export const ACCOUNT_ADD_FAIL = 'ACCOUNT_ADD_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_PAYMENT_REQUEST = 'USER_PAYMENT_REQUEST'
export const USER_PAYMENT_SUCCESS = 'USER_PAYMENT_SUCCESS'
export const USER_PAYMENT_FAIL = 'USER_PAYMENT_FAIL'

export const ACCOUNT_UPDATE_REQUEST = 'ACCOUNT_UPDATE_REQUEST'
export const ACCOUNT_UPDATE_SUCCESS = 'ACCOUNT_UPDATE_SUCCESS'
export const ACCOUNT_UPDATE_FAIL = 'ACCOUNT_UPDATE_FAIL'

export const CANCEL_SUBSCRIPTION_REQUEST = 'CANCEL_SUBSCRIPTION_REQUEST'
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS'
export const CANCEL_SUBSCRIPTION_FAIL = 'CANCEL_SUBSCRIPTION_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const ADD_LIST_REQUEST = 'ADD_LIST_REQUEST'
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS'
export const ADD_LIST_FAIL = 'ADD_LIST_FAIL'

export const REMOVE_LIST_REQUEST = 'REMOVE_LIST_REQUEST'
export const REMOVE_LIST_SUCCESS = 'REMOVE_LIST_SUCCESS'
export const REMOVE_LIST_FAIL = 'REMOVE_LIST_FAIL'