export const DIRECTORS_LIST_REQUEST = 'DIRECTORS_LIST_REQUEST'
export const DIRECTORS_LIST_SUCCESS = 'DIRECTORS_LIST_SUCCESS'
export const DIRECTORS_LIST_FAIL = 'DIRECTORS_LIST_FAIL'

export const DIRECTORS_DETAILS_REQUEST = 'DIRECTORS_DETAILS_REQUEST'
export const DIRECTORS_DETAILS_SUCCESS = 'DIRECTORS_DETAILS_SUCCESS'
export const DIRECTORS_DETAILS_FAIL = 'DIRECTORS_DETAILS_FAIL'
