# Generated by Django 4.2.10 on 2024-04-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genre2_genre3_product_genre_three_product_genre_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_three', to='base.genre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_two', to='base.genre'),
        ),
    ]
